language: node_js
node_js:
  - '10'

services:
  - docker

before_install:
  - npm i @microservices/cli

script:
  - npx oms build
  - |
    output="$(npx oms run --silent compare -a image1=iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg== -a image2=iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg== | jq -c .)"
    if [ "$output" != '{"equal":false,"content":"iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAklEQVR4AewaftIAAAALSURBVGP4z8DwHwAFAAH/LmUt0QAAAABJRU5ErkJggg==","format":"png"}' ] ; then echo "$output"; exit 1; fi
